# Generated by Django 4.2.7 on 2026-04-20 08:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('icon', models.CharField(default='🌾', max_length=50, verbose_name='Icône emoji')),
                ('color', models.CharField(default='#4CAF50', max_length=7, verbose_name='Couleur hex')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du marché')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('price_level', models.CharField(choices=[('low', 'Bas'), ('medium', 'Moyen'), ('high', 'Élevé')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('maintenance', 'En maintenance')], default='active', max_length=20)),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture")),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture')),
                ('market_days', models.CharField(blank=True, max_length=100, verbose_name='Jours de marché')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('products_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marché',
                'verbose_name_plural': 'Marchés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('local_name', models.CharField(blank=True, max_length=200, verbose_name='Nom local (Wolof/Pulaar)')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('tonne', 'Tonne'), ('sac', 'Sac'), ('botte', 'Botte'), ('unite', 'Unité'), ('litre', 'Litre'), ('panier', 'Panier')], default='kg', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, verbose_name='URL image')),
                ('season_start', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Début saison (mois)')),
                ('season_end', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Fin saison (mois)')),
                ('trend', models.CharField(choices=[('up', 'En hausse'), ('down', 'En baisse'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('availability', models.CharField(choices=[('abundant', 'Abondant'), ('normal', 'Normal'), ('scarce', 'Rare'), ('unavailable', 'Indisponible')], default='normal', max_length=15)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Produit vedette')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Population')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Agriculteur'), ('trader', 'Commerçant'), ('consumer', 'Consommateur'), ('analyst', 'Analyste'), ('admin', 'Administrateur')], default='consumer', max_length=15)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('avatar_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof')], default='fr', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.market')),
                ('preferred_products', models.ManyToManyField(blank=True, to='api.product', verbose_name='Produits favoris')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.CharField(choices=[('7d', '7 jours'), ('30d', '30 jours'), ('90d', '90 jours')], default='7d', max_length=5)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Modéré'), ('high', 'Élevé')], default='medium', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.7, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('trend', models.CharField(choices=[('up', 'En hausse'), ('down', 'En baisse'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('recommendation', models.TextField(verbose_name='Recommandation IA')),
                ('analysis', models.TextField(blank=True, verbose_name='Analyse détaillée')),
                ('factors', models.JSONField(default=list, verbose_name="Facteurs d'influence")),
                ('predicted_prices_series', models.JSONField(default=list, verbose_name='Série de prix prédits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions_created', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.product')),
            ],
            options={
                'verbose_name': 'Prédiction',
                'verbose_name_plural': 'Prédictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='market',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='api.region'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('above', 'Prix au-dessus du seuil'), ('below', 'Prix en dessous du seuil'), ('change', 'Variation de prix')], default='above', max_length=10)),
                ('threshold_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix seuil (FCFA)')),
                ('change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Déclenchée'), ('disabled', 'Désactivée')], default='active', max_length=10)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('date', models.DateField(verbose_name='Date')),
                ('source', models.CharField(default='manuel', max_length=100, verbose_name='Source')),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices_added', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.product')),
            ],
            options={
                'verbose_name': 'Prix',
                'verbose_name_plural': 'Prix',
                'ordering': ['-date', 'product'],
                'unique_together': {('product', 'market', 'date')},
            },
        ),
    ]
