# Generated by Django 4.2.7 on 2026-04-26 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.CreateModel(
            name='FarmerSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité vendue')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (FCFA)')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Revenu total (FCFA)')),
                ('sale_date', models.DateTimeField(verbose_name='Date de vente')),
                ('buyer_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'acheteur")),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('mobile', 'Mobile Money'), ('bank', 'Banque')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente agriculteur',
                'verbose_name_plural': 'Ventes agriculteurs',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='CultureGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_season', models.CharField(max_length=100, verbose_name='Saison de plantation')),
                ('harvest_season', models.CharField(max_length=100, verbose_name='Saison de récolte')),
                ('growth_duration', models.IntegerField(verbose_name='Durée de croissance (jours)')),
                ('soil_type', models.CharField(max_length=200, verbose_name='Type de sol')),
                ('water_requirements', models.TextField(verbose_name='Besoins en eau')),
                ('temperature_range', models.CharField(max_length=100, verbose_name='Plage de température')),
                ('materials_needed', models.TextField(verbose_name='Matériaux nécessaires')),
                ('planting_instructions', models.TextField(verbose_name='Instructions de plantation')),
                ('care_instructions', models.TextField(verbose_name="Instructions d'entretien")),
                ('harvest_instructions', models.TextField(verbose_name='Instructions de récolte')),
                ('common_diseases', models.TextField(blank=True, verbose_name='Maladies courantes')),
                ('pest_control', models.TextField(blank=True, verbose_name='Lutte contre les ravageurs')),
                ('yield_per_hectare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rendement par hectare (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='culture_guide', to='api.product')),
            ],
            options={
                'verbose_name': 'Guide de culture',
                'verbose_name_plural': 'Guides de culture',
            },
        ),
        migrations.CreateModel(
            name='FarmerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='Lieu de stockage')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('sold', 'Vendu')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock agriculteur',
                'verbose_name_plural': 'Stocks agriculteurs',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product', 'storage_location')},
            },
        ),
    ]
